In [2]:
import pandas as pd

In [3]:
data = {'country': ['Italy','Spain','Greece','France','Portugal'],
        'popu': [61, 46, 11, 65, 10],
        'percent': [0.83,0.63,0.15,0.88,0.14]}

In [4]:
df = pd.DataFrame(data, index=['ITA', 'ESP', 'GRC', 'FRA', 'PRT'])

In [5]:
print(df)

      country  popu  percent
ITA     Italy    61     0.83
ESP     Spain    46     0.63
GRC    Greece    11     0.15
FRA    France    65     0.88
PRT  Portugal    10     0.14

In [6]:
# renaming

In [9]:
dfnew = df.rename(columns={'popu':'population'})

In [10]:
print(dfnew)

      country  population  percent
ITA     Italy          61     0.83
ESP     Spain          46     0.63
GRC    Greece          11     0.15
FRA    France          65     0.88
PRT  Portugal          10     0.14

In [11]:
# add columns

In [12]:
dfnew['city'] = ['vzm','vksp','gdv','hyd','rjy']

In [13]:
print(dfnew)

      country  population  percent  city
ITA     Italy          61     0.83   vzm
ESP     Spain          46     0.63  vksp
GRC    Greece          11     0.15   gdv
FRA    France          65     0.88   hyd
PRT  Portugal          10     0.14   rjy

In [14]:
# delete columns

In [15]:
del dfnew['city']

In [16]:
print(dfnew)

      country  population  percent
ITA     Italy          61     0.83
ESP     Spain          46     0.63
GRC    Greece          11     0.15
FRA    France          65     0.88
PRT  Portugal          10     0.14

In [17]:
# inserting

In [22]:
ser = pd.Series(['es','it','fr','pt','gr'], index = ['ESP','ITA','FRA','PRT','GRC'])
dfnew.insert(1,'Internet dom',ser)

In [25]:
print(dfnew)

      country Internet dom  population  percent
ITA     Italy           it          61     0.83
ESP     Spain           es          46     0.63
GRC    Greece           gr          11     0.15
FRA    France           fr          65     0.88
PRT  Portugal           pt          10     0.14

In [27]:
# replacing columns

In [28]:
data = {'country': ['Italy','Spain','Greece','France','Portugal'],
        'popu': [61, 46, 11, 65, 10],
        'percent': [0.83,0.63,0.15,0.88,0.14]}

df = pd.DataFrame(data, index=['ITA', 'ESP', 'GRC', 'FRA', 'PRT'])
df.percent = '-'     # A single value 'propagates' to all column cells
df

      country  popu percent
ITA     Italy    61       -
ESP     Spain    46       -
GRC    Greece    11       -
FRA    France    65       -
PRT  Portugal    10       -

In [29]:
df.percent = 0.001*df.popu   # Data in 'percent' and 'popu' columns are autonatically aligned  
df

      country  popu  percent
ITA     Italy    61    0.061
ESP     Spain    46    0.046
GRC    Greece    11    0.011
FRA    France    65    0.065
PRT  Portugal    10    0.010

In [30]:
df1 = pd.read_excel(r"D:\20vv1a1263_2_2\ss.xls")

In [41]:
df2 = df1.groupby(['Customer ID'])

In [43]:
df2.first()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Customer ID,,,,,,,,,,,,,,,,,,,,
AA-10315,1160,CA-2014-147039,2014-06-30,2014-07-05,Standard Class,Alex Avila,Consumer,United States,Minneapolis,Minnesota,55407,Central,OFF-AP-10000576,Office Supplies,Appliances,"Belkin 325VA UPS Surge Protector, 6'",362.940,3,0.0,90.7350
AA-10375,536,CA-2013-126613,2013-07-11,2013-07-17,Standard Class,Allen Armold,Consumer,United States,Mesa,Arizona,85204,West,OFF-ST-10001325,Office Supplies,Storage,Sterilite Officeware Hinged File Box,16.768,2,0.2,1.4672
AA-10480,13,CA-2014-114412,2014-04-16,2014-04-21,Standard Class,Andrew Allen,Consumer,United States,Concord,North Carolina,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
AA-10645,4021,CA-2011-154963,2011-06-22,2011-06-27,Standard Class,Anna Andreadi,Consumer,United States,Chester,Pennsylvania,19013,East,FUR-CH-10004698,Furniture,Chairs,"Padded Folding Chairs, Black, 4/Carton",170.058,3,0.3,-4.8588
AB-10015,4962,CA-2011-156587,2011-03-07,2011-03-08,First Class,Aaron Bergman,Consumer,United States,Seattle,Washington,98103,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XP-21865,482,CA-2011-134677,2011-10-06,2011-10-10,Standard Class,Xylona Preis,Consumer,United States,San Diego,California,92024,West,TEC-AC-10001445,Technology,Accessories,Imation USB 2.0 Swivel Flash Drive USB flash d...,9.090,3,0.0,1.9089
YC-21895,754,CA-2013-110499,2013-04-08,2013-04-10,First Class,Yoseph Carroll,Corporate,United States,San Francisco,California,94110,West,TEC-CO-10002095,Technology,Copiers,Hewlett Packard 610 Color Digital Copier / Pri...,1199.976,3,0.2,374.9925
YS-21880,1394,CA-2014-124828,2014-07-04,2014-07-05,First Class,Yana Sorensen,Corporate,United States,Burlington,North Carolina,27217,South,OFF-AR-10003514,Office Supplies,Art,4009 Highlighters by Sanford,9.552,3,0.2,1.5522
ZC-21910,589,US-2013-156986,2013-03-21,2013-03-25,Standard Class,Zuschuss Carroll,Consumer,United States,Salem,Oregon,97301,West,TEC-PH-10003800,Technology,Phones,i.Sound Portable Power - 8000 mAh,84.784,2,0.2,-20.1362
ZD-21925,19,CA-2011-143336,2011-08-27,2011-09-01,Second Class,Zuschuss Donatelli,Consumer,United States,San Francisco,California,94109,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824

In [39]:
df2 = df1.groupby(['Customer ID','State'])

In [40]:
df2.first()

                        Row ID        Order ID Order Date  Ship Date  \
Customer ID State
AA-10315    California    1300  CA-2012-121391 2012-10-04 2012-10-07
            Minnesota     1160  CA-2014-147039 2014-06-30 2014-07-05
            New York      7469  CA-2011-138100 2011-09-15 2011-09-20
            Texas         5199  CA-2013-103982 2013-03-04 2013-03-09
AA-10375    Arizona        536  CA-2013-126613 2013-07-11 2013-07-17
...                        ...             ...        ...        ...
ZC-21910    Washington     810  CA-2011-151995 2011-10-13 2011-10-15
ZD-21925    California      19  CA-2011-143336 2011-08-27 2011-09-01
            Florida       3815  CA-2013-152471 2013-07-09 2013-07-09
            Indiana       5898  CA-2013-167682 2013-04-04 2013-04-10
            Tennessee     3041  US-2013-147991 2013-05-06 2013-05-10

                             Ship Mode       Customer Name   Segment  \
Customer ID State
AA-10315    California     First Class          Alex Avila  Consumer
            Minnesota   Standard Class          Alex Avila  Consumer
            New York    Standard Class          Alex Avila  Consumer
            Texas       Standard Class          Alex Avila  Consumer
AA-10375    Arizona     Standard Class        Allen Armold  Consumer
...                                ...                 ...       ...
ZC-21910    Washington     First Class    Zuschuss Carroll  Consumer
ZD-21925    California    Second Class  Zuschuss Donatelli  Consumer
            Florida           Same Day  Zuschuss Donatelli  Consumer
            Indiana     Standard Class  Zuschuss Donatelli  Consumer
            Tennessee   Standard Class  Zuschuss Donatelli  Consumer

                              Country           City  Postal Code   Region  \
Customer ID State
AA-10315    California  United States  San Francisco        94109     West
            Minnesota   United States    Minneapolis        55407  Central
            New York    United States  New York City        10011     East
            Texas       United States     Round Rock        78664  Central
AA-10375    Arizona     United States           Mesa        85204     West
...                               ...            ...          ...      ...
ZC-21910    Washington  United States        Edmonds        98026     West
ZD-21925    California  United States  San Francisco        94109     West
            Florida     United States   Jacksonville        32216    South
            Indiana     United States       Richmond        47374  Central
            Tennessee   United States    Chattanooga        37421    South

                             Product ID         Category Sub-Category  \
Customer ID State
AA-10315    California  OFF-ST-10001590  Office Supplies      Storage
            Minnesota   OFF-AP-10000576  Office Supplies   Appliances
            New York    OFF-PA-10000349  Office Supplies        Paper
            Texas       OFF-SU-10000151  Office Supplies     Supplies
AA-10375    Arizona     OFF-ST-10001325  Office Supplies      Storage
...                                 ...              ...          ...
ZC-21910    Washington  OFF-AR-10003190  Office Supplies          Art
ZD-21925    California  OFF-AR-10003056  Office Supplies          Art
            Florida     TEC-PH-10002824       Technology       Phones
            Indiana     FUR-FU-10003799        Furniture  Furnishings
            Tennessee   FUR-FU-10004270        Furniture  Furnishings

                                                             Product Name  \
Customer ID State
AA-10315    California  Tenex Personal Project File with Scoop Front D...
            Minnesota                Belkin 325VA UPS Surge Protector, 6'
            New York                                              Staples
            Texas             High Speed Automatic Electric Letter Opener
AA-10375    Arizona                  Sterilite Officeware Hinged File Box
...                                                                   ...
ZC-21910    Washington                                          Newell 32
ZD-21925    California                                         Newell 341
            Florida              Jabra SPEAK 410 Multidevice Speakerphone
            Indiana                        Seth Thomas 13 1/2" Wall Clock
            Tennessee       Eldon Image Series Desk Accessories, Burgundy

                           Sales  Quantity  Discount    Profit
Customer ID State
AA-10315    California    26.960         2       0.0    7.0096
            Minnesota    362.940         3       0.0   90.7350
            New York      14.940         3       0.0    7.0218
            Texas       3930.072         3       0.2 -786.0144
AA-10375    Arizona       16.768         2       0.2    1.4672
...                          ...       ...       ...       ...
ZC-21910    Washington    11.520         4       0.0    3.2256
ZD-21925    California     8.560         2       0.0    2.4824
            Florida      823.960         5       0.2   51.4975
            Indiana       71.120         4       0.0   22.0472
            Tennessee     16.720         5       0.2    3.3440

[4063 rows x 19 columns]